In [227]:
import pandas as pd

In [228]:
raw = pd.read_csv('/work/Experimental-Psycholinguistics/combined_data.csv')

the .head() command shows tthe amount of rows you want from the top. with no number in the bracket, you get the first five. using .tail() shows you the last five.

In [229]:
#raw.head(20)

In [230]:
list(raw)
# gives you the list of the column names. makes it easy to copy so you can pick the columns that are relevant.

['participant_id',
 'component_num',
 'url',
 'meta',
 'sender',
 'sender_type',
 'sender_id',
 'ended_on',
 'duration',
 'time_run',
 'time_render',
 'time_show',
 'time_end',
 'time_commit',
 'timestamp',
 'time_switch',
 'response',
 'response_action',
 'prime',
 'target',
 'condition',
 'soa_condition',
 'congruence',
 'correct_response',
 'correctResponse',
 'correct']

In [231]:
'participant_id' 'duration' 'sender' 'soa_condition' 'response' 'prime' 'target' 'condition' 'congruence'

'participant_iddurationsendersoa_conditionresponseprimetargetconditioncongruence'

In [232]:
cols = ['participant_id', 'sender', 'duration', 'prime', 'target', 'response', 'condition', 'soa_condition',  'congruence', 'correct_response', 'correct']

In [233]:
df = raw[cols]

In [234]:
df = df[df['sender'] == 'target']

In [235]:
sender_list = list(df['sender'])
set(sender_list)
# set shows the duplicates

{'target'}

In [236]:
df['sender'].unique()
#specific pandas command

<StringArray>
['target']
Length: 1, dtype: str

In [237]:
df = df[df['condition'] != 'practice']
# look through the condition column and find everything that is not practice
# normally Ethan would prefer to have a separate column for practice / not practice

In [238]:
df = df.drop(columns=['sender'])
df
# drop removes the sender column as we no longer need it

,participant_id,duration,prime,target,response,condition,soa_condition,congruence,correct_response,correct
40,51,520.14,roof,PIANO,m,Inc_Synth_Synth,long,incongruent,m,True
47,51,640.66,sheep,BULL,n,Inc_Nat_Nat,long,incongruent,m,False
54,51,597.74,fort,GOAT,n,Inc_Synth_Nat,long,incongruent,n,True
61,51,495.68,pear,PEAR,n,Con_Nat,long,congruent,n,True
68,51,556.86,olive,MOTOR,m,Inc_Nat_Synth,long,incongruent,m,True
...,...,...,...,...,...,...,...,...,...,...
15606,69,699.20,belt,BELT,m,Con_Synth,short,congruent,m,True
15612,69,580.20,daisy,DAISY,n,Con_Nat,short,congruent,n,True
15618,69,577.90,peach,SHED,m,Inc_Nat_Synth,short,incongruent,m,True
15624,69,661.10,rake,HUSKY,n,Inc_Synth_Nat,short,incongruent,n,True
15630,69,709.20,fern,PETAL,n,Inc_Nat_Nat,short,incongruent,n,True

In [239]:
df.loc[df['target'] == 'BULL', 'correct_response'] = 'n'
df.loc[df['target'] == 'BULL', 'correct'] = 'True'
# fixing a mistake in the experiment

In [240]:
df['accuracy']= df['response'] == df['correct_response']
df = df.drop(columns=['correct'])
df

,participant_id,duration,prime,target,response,condition,soa_condition,congruence,correct_response,accuracy
40,51,520.14,roof,PIANO,m,Inc_Synth_Synth,long,incongruent,m,True
47,51,640.66,sheep,BULL,n,Inc_Nat_Nat,long,incongruent,n,True
54,51,597.74,fort,GOAT,n,Inc_Synth_Nat,long,incongruent,n,True
61,51,495.68,pear,PEAR,n,Con_Nat,long,congruent,n,True
68,51,556.86,olive,MOTOR,m,Inc_Nat_Synth,long,incongruent,m,True
...,...,...,...,...,...,...,...,...,...,...
15606,69,699.20,belt,BELT,m,Con_Synth,short,congruent,m,True
15612,69,580.20,daisy,DAISY,n,Con_Nat,short,congruent,n,True
15618,69,577.90,peach,SHED,m,Inc_Nat_Synth,short,incongruent,m,True
15624,69,661.10,rake,HUSKY,n,Inc_Synth_Nat,short,incongruent,n,True
15630,69,709.20,fern,PETAL,n,Inc_Nat_Nat,short,incongruent,n,True

In [241]:
#df_grouped = df.groupby(['soa_condition','congruence']).mean(['duration'])
# i can run .groupby without the .mean, but the result is still odd.
# with .mean, it doesn't work at all. error that calls for Boolean value

In [242]:
#df_grouped = df_grouped.reset_index()
#df_grouped
#should show us a nice, simple pandas dataframe / table

In [243]:
# matplotlib is a powerful package for creating graphs that is really horrible to work with
# seaborn is a package that makes it way simpler to do

In [245]:
%pip install seaborn

Collecting seaborn

  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /opt/conda/lib/python3.13/site-packages (from seaborn) (2.5.2)
Requirement already satisfied: pandas>=1.2 in /opt/conda/lib/python3.13/site-packages (from seaborn) (3.0.5)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /opt/conda/lib/python3.13/site-packages (from seaborn) (3.11.1)
Requirement already satisfied: contourpy>=1.0.1 in /opt/conda/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in /opt/conda/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/conda/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.2)
Requirement already satisfied: pillow>=9 in /opt/conda/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.3.0)
Requirement already satisfied: pyparsing>=3 in /opt/conda/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /opt/conda/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.13/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)

Installing collected packages: seaborn

Successfully installed seaborn-0.13.2

Note: you may need to restart the kernel to use updated packages.

In [246]:
import seaborn as sns

In [247]:
#ax = sns.barplot(data=df_grouped, x = 'soa_condition', y = 'duration', hue = 'congruence')
# = sns.plottype(data=the data in question, x = IV, y = DV, hue = IV2)
# ax is the name of the plot

In [248]:
#sns.move_legend(ax,"lower right")
# this moves the explanation/legend from covering the top to not